#!/bin/bash
export WATCOM=/mnt/c/workspace/open-watcom-v2
export PATH=$WATCOM/build/binl:$PATH
export INCLUDE=$WATCOM/h
export LIB=$WATCOM/lib386

cmake -B build -G "Watcom WMake"                                          -DCMAKE_VERBOSE_MAKEFILE=TRUE -DWOLFSSL_ASM=no -DWOLFSSL_EXAMPLES=no -DWOLFSSL_CRYPT_TESTS=no -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=x86   -DCMAKE_POLICY_DEFAULT_CMP0136=NEW -DCMAKE_WATCOM_RUNTIME_LIBRARY=MultiThreadedDLL || { echo >&2 "Build #1 failed"; exit 1; }

cmake -B build -G "Watcom WMake" -DWOLFSSL_DEBUG_CERTS                    -DCMAKE_VERBOSE_MAKEFILE=TRUE -DWOLFSSL_ASM=no -DWOLFSSL_EXAMPLES=no -DWOLFSSL_CRYPT_TESTS=no -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=x86   -DCMAKE_POLICY_DEFAULT_CMP0136=NEW -DCMAKE_WATCOM_RUNTIME_LIBRARY=MultiThreadedDLL || { echo >&2 "Build #2 failed"; exit 1; }

cmake -B build -G "Watcom WMake" -DDEBUG_WOLFSSL                          -DCMAKE_VERBOSE_MAKEFILE=TRUE -DWOLFSSL_ASM=no -DWOLFSSL_EXAMPLES=no -DWOLFSSL_CRYPT_TESTS=no -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=x86   -DCMAKE_POLICY_DEFAULT_CMP0136=NEW -DCMAKE_WATCOM_RUNTIME_LIBRARY=MultiThreadedDLL || { echo >&2 "Build #3 failed"; exit 1; }

cmake -B build -G "Watcom WMake" -DDEBUG_WOLFSSL -DWOLFSSL_DEBUG_CERTS    -DCMAKE_VERBOSE_MAKEFILE=TRUE -DWOLFSSL_ASM=no -DWOLFSSL_EXAMPLES=no -DWOLFSSL_CRYPT_TESTS=no -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=x86   -DCMAKE_POLICY_DEFAULT_CMP0136=NEW -DCMAKE_WATCOM_RUNTIME_LIBRARY=MultiThreadedDLL || { echo >&2 "Build #3 failed"; exit 1; }

cmake -B build -G "Watcom WMake" -DDEBUG_WOLFSSL -DNO_WOLFSSL_DEBUG_CERTS -DCMAKE_VERBOSE_MAKEFILE=TRUE -DWOLFSSL_ASM=no -DWOLFSSL_EXAMPLES=no -DWOLFSSL_CRYPT_TESTS=no -DCMAKE_SYSTEM_NAME=Windows -DCMAKE_SYSTEM_PROCESSOR=x86   -DCMAKE_POLICY_DEFAULT_CMP0136=NEW -DCMAKE_WATCOM_RUNTIME_LIBRARY=MultiThreadedDLL || { echo >&2 "Build #4 failed"; exit 1; }

echo "All builds successful"
echo "Done! All builds successful"
