#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

CFLAGS +=-DWOLFSSL_USER_SETTINGS
EXTRA_CFLAGS += -DNO_WATCHDOG

PROJECT_NAME := wolfssl_test

include $(IDF_PATH)/make/project.mk

