#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

CFLAGS +=-DWOLFSSL_USER_SETTINGS

PROJECT_NAME := hello-world

include $(IDF_PATH)/make/project.mk

