name: Arduino CI Build

# See https://github.com/wolfSSL/Arduino-wolfSSL

# TODO remove '*' om push/ branches, and uncomment github.repository_owner == 'wolfssl'

# START OF COMMON SECTION
on:
  push:
    branches: [ '*', 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build:
    # if: github.repository_owner == 'wolfssl'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Arduino CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
          echo "$(pwd)/bin" >> $GITHUB_PATH

      - name: Setup Arduino CLI
        run: |
          arduino-cli config init
          arduino-cli core update-index
          arduino-cli config add board_manager.additional_urls https://www.pjrc.com/teensy/package_teensy_index.json
          arduino-cli core update-index
          arduino-cli config add board_manager.additional_urls https://arduino.esp8266.com/stable/package_esp8266com_index.json
          arduino-cli core update-index
          arduino-cli core install esp32:esp32      # ESP32
          arduino-cli core install arduino:avr      # Arduino Uno, Mega, Nano
          arduino-cli core install arduino:sam      # Arduino Due
          arduino-cli core install arduino:samd     # Arduino Zero
          arduino-cli core install teensy:avr       # PJRC Teensy
          arduino-cli core install esp8266:esp8266  # ESP8266
          arduino-cli lib install "ArduinoJson"     # Example dependency
          arduino-cli lib install "WiFiNINA"        # ARDUINO_SAMD_NANO_33_IOT
          arduino-cli lib install "Ethernet"        # Install Ethernet library

          # arduino-cli lib install "wolfSSL"  # Install wolfSSL library from Arduino

          # Install current wolfSSL as an Arduino library:
          echo "Checking Arduino library directories..."
          pushd IDE/ARDUINO
          bash wolfssl-arduino.sh INSTALL  # Install wolfSSL library
          popd

      # This will fail with Arduino published wolfSSL v5.7.6 and older
      # See https://github.com/wolfSSL/wolfssl/pull/8514
      # Pending: "arduino:sam:arduino_due_x"
      - name: Compile Arduino Sketches for various boards
        run: |
          SUCCESS=true
          for BOARD in "arduino:avr:uno" "esp32:esp32:esp32"  "arduino:avr:mega" "arduino:avr:nano" "arduino:samd:arduino_zero_native" "esp8266:esp8266:generic" "teensy:avr:teensy40"; do
            echo "Compiling for $BOARD"
            for EXAMPLE in $(find IDE/ARDUINO/sketches -mindepth 1 -maxdepth 1 -type d); do
              if [[ "$BOARD" =~ "arduino:avr:uno"|"arduino:avr:mega"|"arduino:avr:nano" && ( "$EXAMPLE" =~ "wolfssl_server" || "$EXAMPLE" =~ "wolfssl_client" || "$EXAMPLE" =~ "test" ) ]]; then
                echo "Skipping $EXAMPLE for $BOARD (No WiFi support)"
                continue
              fi

              if  [[ "$BOARD" =~ "arduino:avr:uno"|"arduino:avr:nano" && ( "$EXAMPLE" != "template" ) && ( "$EXAMPLE" != "wolfssl_version" ) ]]; then
                echo "Skipping $EXAMPLE for $BOARD (memory limited)"
                continue
              fi


              echo "Compiling $EXAMPLE for $BOARD"
              arduino-cli compile --fqbn $BOARD "$EXAMPLE"
              EXIT_CODE=$?
              if [ "$EXIT_CODE" -ne 0 ]; then
                echo "❌ Compilation failed for $EXAMPLE on $BOARD (Exit code: $EXIT_CODE)"
                SUCCESS=false
              else
                echo "✅ Compilation succeeded for $EXAMPLE on $BOARD"
              fi
            done
          done

          if [ "$SUCCESS" = true ]; then
            echo "✅ All sketches compiled successfully!"
          else
            echo "❌ One or more sketches failed to compile."
            exit 1
          fi

      - name: Upload Compilation Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-sketch
          path: IDE/ARDUINO/sketches/template/build/*
