name: Espressif examples tests
# START OF COMMON SECTION
on:
  push:
    branches: [ '*', 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  validate-kconfig:

    name: Validate component Kconfig files
    if: github.repository_owner == 'gojimmypi'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
        - name: Check each example Kconfig file
          uses: actions/checkout@v4

        - name: Install kconfiglib
          run: python3 -m pip install kconfiglib

        - run: |
            # assume success unless proven otherwise
            FAIL=0

            # Start from Espressif example root
            cd $GITHUB_WORKSPACE/IDE/Espressif/ESP-IDF/
            echo "Searching for examples in $(pwd)/examples"

            # Validate all example wolfssl component Kconfig files
            for dir in ./examples/*/; do
              THIS_KCONFIG="$dir/components/wolfssl/Kconfig"
              if [[ -f "$THIS_KCONFIG" ]]; then
                echo "Validating $THIS_KCONFIG"
                ./validate_Kconfig.py "$THIS_KCONFIG"
                if [[ $? -ne 0 ]]; then
                  echo "Validation failed for $THIS_KCONFIG"
                  FAIL=1
                fi
              else
                echo "No Kconfig found in $dir"
                FAIL=1
              fi
            done # for dir

            # Final check
            if [[ $FAIL -ne 0 ]]; then
              echo "❌ One or more Kconfig files failed validation."
              exit 1
            else
              echo "✅ All Kconfig files passed validation."
              exit 0
            fi
  espressif_latest:
    needs: validate-kconfig
    name: latest Docker container
    if: github.repository_owner == 'gojimmypi'
    runs-on: ubuntu-22.04
    # This should be a safe limit for the tests to run.
    timeout-minutes: 12
    container:
      image: espressif/idf:latest
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: |
          cd /opt/esp/idf
          . ./export.sh &&
          cd $GITHUB_WORKSPACE/IDE/Espressif/ESP-IDF/
          ./compileAllExamples.sh
  espressif_v4_4:
    needs: validate-kconfig
    name: v4.4 Docker container
    if: github.repository_owner == 'gojimmypi'
    runs-on: ubuntu-22.04
    container:
      image: espressif/idf:release-v4.4
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: cd /opt/esp/idf && . ./export.sh && cd $GITHUB_WORKSPACE; IDE/Espressif/ESP-IDF/compileAllExamples.sh
  espressif_v5_0:
    needs: validate-kconfig
    name: v5.0 Docker container
    if: github.repository_owner == 'gojimmypi'
    runs-on: ubuntu-22.04
    container:
      image: espressif/idf:release-v5.0
    steps:
      - uses: actions/checkout@v4
      - name: Initialize Espressif IDE and build examples
        run: cd /opt/esp/idf && . ./export.sh && cd $GITHUB_WORKSPACE; IDE/Espressif/ESP-IDF/compileAllExamples.sh
