name: Build for .NET 3.5

on:
  push:
    branches:
      - dev-35  # Trigger only on commits to dev-35 in your repo
  pull_request:
    branches:
      - dev-35
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019  # .NET 3.5 is available here

    steps:
      - name: Checkout Repository (dev-35 branch)
        uses: actions/checkout@v3
        with:
          ref: dev-35  # Ensures correct branch is checked out

      - name: Ensure Visual Studio project files are UTF-8 with CRLF
        shell: bash
        run: |
          echo "Checking encoding..."
          for file in $(git ls-files '*.vcxproj' '*.csproj' '*.sln'); do
            encoding=$(file -bi "$file" | grep -o 'charset=.*' | cut -d= -f2)
            if [ "$encoding" != "utf-8" ]; then
              echo "ERROR: $file is not UTF-8 encoded"
              exit 1
            fi
          done

          echo "Checking line endings..."
          for file in $(git ls-files '*.vcxproj' '*.csproj' '*.sln'); do
            if grep -IL . "$file"; then
              echo "ERROR: $file contains non-text content"
              exit 1
            fi
            if ! grep -q $'\r'$'\n' "$file"; then
              echo "ERROR: $file does not have CRLF line endings"
              exit 1
            fi
          done

      - name: Checkout wolfSSL (dev-35 branch)
        uses: actions/checkout@v3
        with:
          repository: gojimmypi/wolfssl
          ref: dev-35
          path: wolfssl  # Clone wolfSSL into the "wolfssl" subdirectory

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

        # wolfssl core
      - name: Build wolfSSL (DLL Debug, x64)
        working-directory: wolfssl
        run: |
          msbuild wolfssl.vcxproj /p:Configuration="DLL Debug" /p:Platform=x64 /p:PlatformToolset=v142 /m /verbosity:normal
        shell: cmd

        # C# Wrapper
      - name: Build wolfSSL_CSharp
        working-directory: wrapper/CSharp/wolfSSL_CSharp
        run: msbuild wolfSSL_CSharp.csproj /p:TargetFrameworkVersion=v3.5

        # wolfCrypt-Test
      - name: Build wolfCrypt-Test
        working-directory: wrapper/CSharp/wolfCrypt-Test
        run: msbuild wolfCrypt-Test.csproj /p:TargetFrameworkVersion=v3.5

        # DTLS
        # TODO wolfSSL-DTLS-Client
      - name: Build wolfSSL-DTLS-Server
        working-directory: wrapper/CSharp/wolfSSL-DTLS-Server
        run: msbuild wolfSSL-DTLS-Server.csproj /p:TargetFrameworkVersion=v3.5

        # DTLS-PSK
        # TODO wolfSSL-DTLS-PSK-Client
      - name: Build wolfSSL-DTLS-PSK-Server
        working-directory: wrapper/CSharp/wolfSSL-DTLS-PSK-Server
        run: msbuild wolfSSL-DTLS-PSK-Server.csproj /p:TargetFrameworkVersion=v3.5

        # TLS
      - name: Build wolfSSL-TLS-Client
        working-directory: wrapper/CSharp/wolfSSL-TLS-Client
        run: msbuild wolfSSL-TLS-Client.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-Server
        working-directory: wrapper/CSharp/wolfSSL-TLS-Server
        run: msbuild wolfSSL-TLS-Server.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-ServerThreaded
        working-directory: wrapper/CSharp/wolfSSL-TLS-ServerThreaded
        run: msbuild wolfSSL-TLS-ServerThreaded.csproj /p:TargetFrameworkVersion=v3.5

        # TLS PSK
      - name: Build wolfSSL-TLS-PSK-Client
        working-directory: wrapper/CSharp/wolfSSL-TLS-PSK-Client
        run: msbuild wolfSSL-TLS-PSK-Client.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-PSK-Server
        working-directory: wrapper/CSharp/wolfSSL-TLS-PSK-Server
        run: msbuild wolfSSL-TLS-PSK-Server.csproj /p:TargetFrameworkVersion=v3.5

        # Example-IOCallbacks
      - name: Build wolfSSL-Example-IOCallbacks
        working-directory: wrapper/CSharp/wolfSSL-Example-IOCallbacks
        run: msbuild wolfSSL-Example-IOCallbacks.csproj /p:TargetFrameworkVersion=v3.5
