name: Self-Hosted Runner Test

# START OF COMMON SECTION
on:
  push:
    branches:
      - ED25519_SHA2_fix
# END OF COMMON SECTION

jobs:
  test:
    # Don't run this on downstream forks:
    if: github.repository_owner == 'gojimmypi'
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          echo "apt-get install shellcheck"
          ls /mnt/c/github

      - name: Run tests
        run: |
          whoami

      - name: Send repository dispatch to wolfssl-actions
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: token ${{ secrets.WOLFSSL_ACTION_TOKEN }}" \
          https://api.github.com/repos/gojimmypi/wolfssl-actions/dispatches \
          -d '{"event_type":"espressif_test"}'

