name: Build and Test for .NET 3.5

on:
  push:
    branches:
      - dev-35  # Trigger only on commits to dev-35 in your repo
  pull_request:
    branches:
      - dev-35
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019  # .NET 3.5 is available here

    steps:
      - name: Checkout Repository (dev-35 branch)
        uses: actions/checkout@v3
        with:
          ref: dev-35  # Ensures correct branch is checked out

      - name: Checkout wolfSSL (dev-35 branch)
        uses: actions/checkout@v3
        with:
          repository: gojimmypi/wolfssl
          ref: dev-35
          path: wolfssl  # Clone wolfSSL into the "wolfssl" subdirectory

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Build Solution
        working-directory: wrapper/CSharp
        run: msbuild wolfSSL_CSharp.sln /p:TargetFrameworkVersion=v3.5 /m /verbosity:minimal

      - name: Run Tests (if present)
        working-directory: wrapper/CSharp
        run: |
          if exist "wolfSSL_Tests\bin\Debug\wolfSSL_Tests.dll" (
            echo "Running Tests..."
            vstest.console.exe wolfSSL_Tests\bin\Debug\wolfSSL_Tests.dll
          ) else (
            echo "No test project found, skipping tests."
          )
