name: Build for .NET 3.5

# START OF COMMON SECTION
on:
  push:
    branches: [ 'master', 'main', 'release/**' ]
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# END OF COMMON SECTION

jobs:
  build:
    if: github.repository_owner == 'wolfssl'
    runs-on: windows-2019  # .NET 3.5 is available here

    steps:
      # Checkout PR branch (supports both forks and local PRs)
      - name: Checkout Repository (PR branch or push branch)
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}

      # Checkout wolfSSL (PR branch if from fork, master if push)
      - name: Checkout wolfSSL (PR branch or master)
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || 'wolfssl/wolfssl' }}  # Pull from fork if PR exists
          ref: ${{ github.event.pull_request.head.ref || 'master' }}  # Use PR branch if available, otherwise master
          path: wolfssl  # Clone wolfSSL into "wolfssl" subdirectory

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      # wolfSSL core
      - name: Build wolfSSL (DLL Debug, x64)
        working-directory: wolfssl
        run: |
          msbuild wolfssl.vcxproj /p:Configuration="DLL Debug" /p:Platform=x64 /p:PlatformToolset=v142 /m /verbosity:normal
        shell: cmd

      # C# Wrapper
      - name: Build wolfSSL_CSharp
        working-directory: wrapper/CSharp/wolfSSL_CSharp
        run: msbuild wolfSSL_CSharp.csproj /p:TargetFrameworkVersion=v3.5

      # wolfCrypt-Test
      - name: Build wolfCrypt-Test
        working-directory: wrapper/CSharp/wolfCrypt-Test
        run: msbuild wolfCrypt-Test.csproj /p:TargetFrameworkVersion=v3.5

      # DTLS
      - name: Build wolfSSL-DTLS-Server
        working-directory: wrapper/CSharp/wolfSSL-DTLS-Server
        run: msbuild wolfSSL-DTLS-Server.csproj /p:TargetFrameworkVersion=v3.5

      # DTLS-PSK
      - name: Build wolfSSL-DTLS-PSK-Server
        working-directory: wrapper/CSharp/wolfSSL-DTLS-PSK-Server
        run: msbuild wolfSSL-DTLS-PSK-Server.csproj /p:TargetFrameworkVersion=v3.5

      # TLS
      - name: Build wolfSSL-TLS-Client
        working-directory: wrapper/CSharp/wolfSSL-TLS-Client
        run: msbuild wolfSSL-TLS-Client.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-Server
        working-directory: wrapper/CSharp/wolfSSL-TLS-Server
        run: msbuild wolfSSL-TLS-Server.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-ServerThreaded
        working-directory: wrapper/CSharp/wolfSSL-TLS-ServerThreaded
        run: msbuild wolfSSL-TLS-ServerThreaded.csproj /p:TargetFrameworkVersion=v3.5

      # TLS PSK
      - name: Build wolfSSL-TLS-PSK-Client
        working-directory: wrapper/CSharp/wolfSSL-TLS-PSK-Client
        run: msbuild wolfSSL-TLS-PSK-Client.csproj /p:TargetFrameworkVersion=v3.5

      - name: Build wolfSSL-TLS-PSK-Server
        working-directory: wrapper/CSharp/wolfSSL-TLS-PSK-Server
        run: msbuild wolfSSL-TLS-PSK-Server.csproj /p:TargetFrameworkVersion=v3.5

      # Example-IOCallbacks
      - name: Build wolfSSL-Example-IOCallbacks
        working-directory: wrapper/CSharp/wolfSSL-Example-IOCallbacks
        run: msbuild wolfSSL-Example-IOCallbacks.csproj /p:TargetFrameworkVersion=v3.5
